---
subsys:
  name: traefik
  type: bosh-deployment

input_resources:
  - name: traefik-boshrelease
    type: git
    uri: https://github.com/gstackio/traefik-boshrelease.git
    version: master


main_deployment_file: traefik-boshrelease/deployment/traefik-deployment.yml

operations_files:
  10.traefik-boshrelease:
    - deployment/operations/cf-integration
    # - deployment/operations/disable-default-tls-certificate
    # - deployment/operations/enable-lets-encrypt # broken now that TLS-SNI has been shut down
    - deployment/operations/enable-web-backend
  local:
    - set-versions
    - activate-debug
    - inject-variables


deployment_vars:
  deployment_name: easyfoundry-traefik

  traefik_domain: easyfoundry.prototyp.it

  acme_certs_email: acme-certs@gstack.io
  acme_staging: true

  web_backend_hostname: traefik.easyfoundry.prototyp.it
  web_backend_username: gstack
  web_backend_md5_htpasswd: $apr1$exP13HG4$eJjE8uEIVmmS8o1mKCfL5.

  # stemcell_name: bosh-warden-boshlite-ubuntu-trusty-go_agent
  # stemcell_version: "3541.12"
  # stemcell_sha1: 14bd6dd50d3caa913af97846eab39e5075b240d7


imported_vars:
  - subsys: cf
    imports:
      - name: stemcell_name
        from: depl-vars
        path: /stemcell_name
      - name: stemcell_version
        from: depl-vars
        path: /stemcell_version
      - name: stemcell_sha1
        from: depl-vars
        path: /stemcell_sha1
