---
subsys:
  name: traefik
  type: bosh-deployment

input_resources:
  - name: traefik-boshrelease
    type: git
    uri: https://github.com/gstackio/traefik-boshrelease.git
    version: 9b8c5ca # master after version 1.2.0


main_deployment_file: traefik-boshrelease/deployment/traefik-deployment.yml

operations_files:
  10.traefik-boshrelease:
    - deployment/operations/rename-deployment
    - deployment/operations/rename-network
    - deployment/operations/cf-integration
    - deployment/operations/enable-lets-encrypt
    - deployment/operations/enable-web-backend
    # - deployment/operations/enable-web-backend-tls # to disable when using the cf-integration above
    - deployment/operations/static-ip
    # - deployment/operations/latest-release
  20.local:
    - pin-stemcell
    - scale-disk
    # - activate-debug


deployment_vars:
  deployment_name: easyfoundry-traefik


  # User-facing settings

  traefik_domain: easyfoundry.prototyp.it
  web_backend_hostname: traefik.easyfoundry.prototyp.it

  acme_certs_email: acme-certs@gstack.io
  acme_staging: true

  web_backend_username: gstack

  # static_ip: ~      # imported below


  # Versions

  stemcell_name: bosh-warden-boshlite-ubuntu-trusty-go_agent
  stemcell_version: "3586.24"
  stemcell_sha1: 32c1e09391d509d24026e55555df07a166f8b8eb
  # stemcell_name:    # imported below
  # stemcell_version: # imported below
  # stemcell_sha1:    # imported below


  # Reference declarations

  network_name: default


imported_vars:
  - subsys: base-env
    imports:
      - name: static_ip
        from: depl-vars
        path: /web_router_ip
  # - subsys: cf
  #   imports:
  #     - name: stemcell_name
  #       from: depl-vars
  #       path: /stemcell_name
  #     - name: stemcell_version
  #       from: depl-vars
  #       path: /stemcell_version
  #     - name: stemcell_sha1
  #       from: depl-vars
  #       path: /stemcell_sha1
