---
subsys:
  name: traefik
  type: bosh-deployment
  depends_on: []

input_resources:
  - name: traefik-boshrelease
    type: git
    uri: https://github.com/gstackio/traefik-boshrelease.git
    version: v1.6.0
    # version: master # when 'developing' is 'true'


developing: false


main_deployment_file: traefik-boshrelease/deployment/traefik-deployment.yml

operations_files:
  10_traefik-boshrelease:
    # - deployment/operations/latest-release               # when 'developing' is 'true'
    # - deployment/operations/testflight/smoke-tests-setup # when 'developing' is 'true'
    - deployment/operations/cf-integration
    - deployment/operations/enable-lets-encrypt
    - deployment/operations/enable-api
    - deployment/operations/enable-rest # required by the smoke tests
    - deployment/operations/static-ip
  20_local:
    # - activate-debug # when 'developing' is 'true'
    - pin-stemcell
    - pin-versions
    - scale-disk
    - additional-alternative-names
    - setup-smoke-tests

variables_files:
  10_local:
    - file: private-config
      example:
        # User-facing settings
        traefik_domain: easyfoundry.example.com
        acme_certs_email: acme-certs@example.com
        api_username: admin


deployment_vars:
  deployment_name: easyfoundry-traefik


  # Debugging

  acme_staging: true


  # Versions

  stemcell_name: bosh-warden-boshlite-ubuntu-xenial-go_agent
  stemcell_os: ubuntu-xenial
  stemcell_version: "456.27"
  stemcell_sha1: 518b991efb9d1e5fb2c861e7c180e076ae66f76e
  # stemcell_os:      # imported below
  # stemcell_version: # imported below
  # stemcell_sha1:    # imported below


  # Reference declarations

  network_name: default


imported_vars:
  - subsys: traefik
    imports:
      # Note: this is actually an auto-import trick in order to inject a value
      # from private-config.yml into the 'web_backend_hostname' variable
      - name: web_backend_hostname
        from: vars-file
        file: private-config
        value: traefik.((traefik_domain))
      - name: smoke_tests_frontend_hostname
        from: vars-file
        file: private-config
        value: smoke-tests-6713.((traefik_domain))

  - subsys: ddbox-standalone-garden-env # instead of generic 'base-env', to be fixed
    imports:
      - name: static_ip
        from: depl-vars
        path: /web_router_ip

  - subsys: cf
    imports:
      # - name: stemcell_os
      #   from: depl-vars
      #   path: /stemcell_os
      # - name: stemcell_version
      #   from: depl-vars
      #   path: /stemcell_version
      # - name: stemcell_sha1
      #   from: depl-vars
      #   path: /stemcell_sha1

      - name: bpm_version
        from: depl-vars
        path: /bpm_version
      - name: bpm_sha1
        from: depl-vars
        path: /bpm_sha1

  - subsys: concourse
    imports:
      - name: concourse_external_host
        from: depl-vars
        path: /external_host
