---
subsys:
  name: traefik
  type: bosh-deployment
  depends_on: []

input_resources:
  - name: traefik-boshrelease
    type: git
    uri: https://github.com/gstackio/traefik-boshrelease.git
    version: "1b1bf77" # v1.13.0 (Traefik v1.7.24) with compiled release for stemcell v621.84
    # version: master # when switching to 'developing: true'


# developing: true


main_deployment_file: traefik-boshrelease/deployment/traefik.yml

operations_files:
  10_traefik-boshrelease:
    # - deployment/operations/latest-release               # when switching to 'developing: true'
    # - deployment/operations/testflight/smoke-tests-setup # when switching to 'developing: true'
    # - deployment/operations/clustering
    - deployment/operations/cf-integration
    - deployment/operations/enable-lets-encrypt
    - deployment/operations/enable-api  # required by the smoke tests
    - deployment/operations/enable-rest # required by the smoke tests
    - deployment/operations/static-ip
  20_local:
    # - activate-debug # when switching to 'developing: true'
    - pin-stemcell
    - pin-versions
    - scale-disk
    - additional-alternative-names
    - setup-smoke-tests
    # - cluster-static-ips
    # - disable-client-cert-auth-on-consul-https-ui-not-recommended

variables_files:
  10_local:
    - file: private-config
      example:
        # User-facing settings
        traefik_domain: easyfoundry.example.com
        acme_certs_email: acme-certs@example.com
        api_username: admin


deployment_vars:
  deployment_name: easyfoundry-traefik


  static_ip2: "10.244.0.44"
  static_ip3: "10.244.0.45"


  # Debugging

  acme_staging: true


  # Versions

  stemcell_name: bosh-warden-boshlite-ubuntu-xenial-go_agent
  stemcell_os: ubuntu-xenial
  stemcell_version: "621.84"
  stemcell_sha1: 305497923033888fd8186aa257e15bc382f2067e


  # Reference declarations

  network_name: default


imported_vars:
  - subsys: traefik
    imports:
      # Note: the following “imports” are actually an “auto-import trick”,
      # that eallow us to inject a value from 'private-config.yml' into the
      # 'web_backend_hostname' variable
      - name: web_backend_hostname
        from: vars-file
        file: private-config
        value: traefik.((traefik_domain))
      - name: smoke_tests_frontend_hostname
        from: vars-file
        file: private-config
        value: smoke-tests-6713.((traefik_domain))

  - subsys: ddbox-standalone-garden-env # instead of generic 'base-env', to be fixed
    imports:
      - name: static_ip
        from: depl-vars
        path: /web_router_ip

  - subsys: cf
    imports:
      - name: bpm_version
        from: depl-vars
        path: /bpm_version
      - name: bpm_sha1
        from: depl-vars
        path: /bpm_sha1

  - subsys: concourse
    imports:
      - name: concourse_external_host
        from: vars-file
        file: private-config
        path: /external_host
