---

- path: /instance_groups/name=shield/jobs/name=shield-daemon/properties/domain?
  type: replace
  value: ((shield_hostname)).((cf_system_domain))

- path: /variables/name=shield-tls/options/alternative_names/-
  type: replace
  value: ((shield_hostname)).((cf_system_domain))



- path: /instance_groups/name=shield/jobs/name=shield-daemon/properties/port?
  type: replace
  # Note: we force this port value here in order to be sure that we use the
  # same value below when registering our route.
  value: &shield_port 20443



- path: /releases/name=routing?
  type: replace
  value:
    name: routing
    version: ((routing_version))
    url: https://bosh.io/d/github.com/cloudfoundry/cf-routing-release?v=((routing_version))
    sha1: ((routing_sha1))

- type: replace
  path: /instance_groups/name=shield/jobs/name=route_registrar?
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: ((cf_deployment_name))
    properties:
      route_registrar:
        routes:
        - name: ((deployment_name))
          tls_port: *shield_port
          server_cert_domain_san: ((shield_hostname)).((cf_system_domain))
          registration_interval: 20s
          uris: [ ((shield_hostname)).((cf_system_domain)) ]

# NOTE: Routing release v0.180.0 and above require BPM to be colocated with
# the 'route_registrar' job.
#
# See: https://github.com/cloudfoundry/routing-release/releases/tag/0.180.0
#
- path: /instance_groups/name=shield/jobs/name=bpm?
  type: replace
  value:
    name: bpm
    release: bpm

- path: /releases/name=bpm?
  type: replace
  value:
    name: bpm
    version: ((bpm_version))
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=((bpm_version))
    sha1: ((bpm_sha1))
