---

# Default target for SHIELD PostgreSQL database

- path: /instance_groups/name=shield/jobs/name=shield-agent/properties/targets?/shield-postgres-db
  type: replace
  value:
    name: (deployment)/(name)-(index)-db
    plugin: postgres
    config:
      pg_user: shieldadmin
      pg_password: ((db-password))
      pg_host: "127.0.0.1"
      pg_database: shielddb


# Default store (for tests only)

- path: /instance_groups/name=shield/jobs/name=shield-agent/properties/stores?/test-fs-store
  type: replace
  value:
    name: test-fs-store
    plugin: fs
    config:
      base_dir: /var/vcap/store/shield-backups


# Default schedules

- path: /instance_groups/name=shield/jobs/name=shield-agent/properties/schedules
  type: replace
  value:
    hourly-00: hourly at 00
    hourly-15: hourly at 15
    hourly-30: hourly at 30
    hourly-45: hourly at 45
    daily: daily 4am
    weekly: sundays 6am
    monthly: 1st sunday at 8am


# Default retentions

- path: /instance_groups/name=shield/jobs/name=shield-agent/properties/retention-policies
  type: replace
  value:
    week:   7d
    month: 31d
    year: 366d
