---

- path: /instance_groups/name=credhub/jobs/name=credhub_exporter?
  type: replace
  value:
    name: credhub_exporter
    release: prometheus
    consumes:
      credhub: "nil" # deactivate linking because credhub_exporter_ctl is buggy about this
    properties:
      credhub_exporter:
        credhub:
          api_url: https://credhub.service.concourse.internal:((credhub_tls_port))
          client_id: credhub-exporter-to-credhub
          client_secret: "((credhub-exporter-to-credhub-client-secret))"
          ca_certs: ((credhub-tls.ca))
        metrics:
          deployment: ((deployment_name))
          environment: "((metrics_environment))"
        skip_ssl_verify: false
        # filters:
        #   generic-certificates:
        #     - "/static/.*"

- path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/credhub-exporter-to-credhub?
  type: replace
  value:
    override: true
    authorized-grant-types: client_credentials,password,refresh_token
    scope: ""
    authorities: credhub.read
    access-token-validity: 600
    refresh-token-validity: 3600
    secret: ((credhub-exporter-to-credhub-client-secret))

- path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/authorization/permissions/-
  type: replace
  value:
    path: /*
    actors: [ uaa-client:credhub-exporter-to-credhub ]
    operations: [ read ]

- path: /variables/name=credhub-exporter-to-credhub-client-secret?
  type: replace
  value:
    name: credhub-exporter-to-credhub-client-secret
    type: password



- path: /instance_groups/name=db/jobs/name=postgres_exporter?
  type: replace
  value:
    name: postgres_exporter
    release: prometheus
    properties:
      postgres_exporter:
        datasource_name: postgresql://grafana:((postgres_grafana_password))@127.0.0.1:5432/?sslmode=require

- path: /instance_groups/name=db/jobs/name=postgres/properties/databases/roles/name=grafana?
  type: replace
  value:
    name: grafana
    password: ((postgres_grafana_password))

- path: /variables/name=postgres_grafana_password?
  type: replace
  value:
    name: postgres_grafana_password
    type: password



- path: /releases/name=prometheus?
  type: replace
  value:
    name: prometheus
    version: ((prometheus_version))
    url: https://bosh.io/d/github.com/cloudfoundry-community/prometheus-boshrelease?v=((prometheus_version))
    sha1: ((prometheus_sha1))
