---

# Releases versions

- path: /releases/name=bpm
  type: replace
  value:
    name: bpm
    version: ((bpm_version))
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=((bpm_version))
    sha1: ((bpm_sha1))
