---

- path: /releases/name=routing?
  type: replace
  value:
    name: routing
    version: ((routing_version))
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=((routing_version))
    sha1: ((routing_sha1))

- type: replace
  path: /instance_groups/name=nginx/jobs/name=route_registrar?
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: ((cf_deployment_name))
    properties:
      route_registrar:
        routes:
          - name: ((deployment_name))-grafana
            port: 3000
            registration_interval: 20s
            uris: [ ((grafana_domain)) ]
          - name: ((deployment_name))-prometheus
            port: 9090
            registration_interval: 20s
            uris: [ ((prometheus_domain)) ]
          - name: ((deployment_name))-alertmanager
            port: 9093
            registration_interval: 20s
            uris: [ ((alertmanager_domain)) ]
