#!/usr/bin/env bash

set -euo pipefail

function main() {
    setup

    local external_host # credhub_ip credhub_port
    external_host=$(priv_cfg_var "/external_host")
    # credhub_ip=$(own_spec_var /deployment_vars/credhub_ip0) # or credhub_ip1
    # credhub_port=$(own_spec_var /deployment_vars/credhub_tls_port)

    echo "CREDHUB_CLIENT=\"credhub-admin\""
    echo "CREDHUB_SECRET=\"$(creds_var "/credhub-admin-client-secret")\""
    # echo "CREDHUB_SERVER=\"https://${credhub_ip}:${credhub_port}\""
    echo "CREDHUB_SERVER=\"https://credhub.${external_host}\""
    cd "${SUBSYS_DIR}" || exit 115
    echo "CREDHUB_CA_CERT=\"$(creds_var "/concourse-internal-ca/certificate" &&
                        echo && ( creds_var "/concourse-external-ca/certificate" 2> /dev/null || true ) &&
                        echo && creds_var "/traefik_ca_cert" &&
                        echo && cat "${SUBSYS_DIR}/conf/fakelerootx1.pem")\""
    # echo "CREDHUB_CA_CERT=\"$(creds_var "/concourse-internal-ca/certificate" && echo && creds_var "/concourse-external-ca/certificate" && echo && cat fakeleintermediatex1.pem fakelerootx1.pem)\""
    echo "export CREDHUB_CLIENT CREDHUB_SECRET CREDHUB_SERVER CREDHUB_CA_CERT"
}

function setup() {
    SUBSYS_DIR=${SUBSYS_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}
    cd "${SUBSYS_DIR}" || exit 115
    BASE_DIR=${BASE_DIR:-$(git rev-parse --show-toplevel)}
    SUBSYS_NAME=$(own_spec_var /subsys/name)
    readonly SUBSYS_DIR BASE_DIR SUBSYS_NAME
}

function priv_cfg_var() {
    local path=$1
    bosh int "${SUBSYS_DIR}/conf/private-config.yml" --path "${path}"
}

function own_spec_var() {
    local path=$1
    bosh int "${SUBSYS_DIR}/conf/spec.yml" --path "${path}"
}

function state_var() {
    local state_file=$1
    local path=$2
    bosh int "${BASE_DIR}/state/${SUBSYS_NAME}/${state_file}.yml" --path "${path}"
}

function creds_var() {
    state_var "depl-creds" "$1"
}

main "$@"
