#!/usr/bin/env bash

set -euo pipefail

SUBSYS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
readonly SUBSYS_DIR
BASE_DIR=$(cd "$SUBSYS_DIR/../.." && pwd)
readonly BASE_DIR

function spec_var() {
    local path=$1
    bosh int "$SUBSYS_DIR/conf/spec.yml" --path "$path"
}

SUBSYS_NAME=$(spec_var /subsys/name)
readonly SUBSYS_NAME

function state_var() {
    local state_file=$1
    local path=$2
    bosh int "$BASE_DIR/state/$SUBSYS_NAME/$state_file.yml" --path "$path"
}

function depl_var() {
    state_var depl-manifest "$1"
}

function creds_var() {
    state_var depl-creds "$1"
}

concourse_domain=$(spec_var /deployment_vars/concourse_domain)
atc_username=$(spec_var /deployment_vars/atc_basic_auth_username)
atc_password=$(creds_var /atc_basic_auth_password)

if [[ ! -e $BASE_DIR/bin/fly ]]; then
	"$SUBSYS_DIR/fetch-fly-cli"
fi

"$BASE_DIR/bin/fly" -t ef login -k -c "https://$concourse_domain" \
	-u "$atc_username" -p "$atc_password"
login_status=$?

if [[ $login_status -eq 0 ]]; then echo OK; else echo ERROR; fi
exit $login_status
