#!/usr/bin/env bash

set -euo pipefail

SUBSYS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
readonly SUBSYS_DIR

pipeline=$(cat <<EOF
---
resources:
  - name: test-resource
    type: time
    source:
      interval: 1m

  - name: test-image
    type: docker-image
    source:
      repository: ubuntu

jobs:
  - name: test-job
    plan:
      - get: test-resource
      - get: test-image
      - task: test-task
        image: test-image
        config:
          platform: linux

          run:
            path: bash
            args: [ "-ec", "echo 'Concourse rocks!'" ]
EOF
)

pipeline_name=self-sanity-tests
concourse_target=ef

set -x

if ! fly -t "$concourse_target" status; then
    "$SUBSYS_DIR/fly-login"
fi

fly -t "$concourse_target" set-pipeline -n -p "$pipeline_name" -c <(set +x; echo "$pipeline"; set -x)

fly -t "$concourse_target" unpause-pipeline -p "$pipeline_name"

fly -t "$concourse_target" trigger-job -j "$pipeline_name/test-job" -w

fly -t "$concourse_target" destroy-pipeline -n -p "$pipeline_name" > /dev/null
