local_operations=(
    inject-variables
    set-versions
    customize-service
)
upstream_operations=(
    operations/bosh-lite
    operations/add-broker
    operations/no-arbitrator
    operations/register-proxy-route
)
