---

- path: /releases/name=routing?
  type: replace
  value:
    name: routing
    version: ((routing_version))
    url: https://bosh.io/d/github.com/cloudfoundry/cf-routing-release?v=((routing_version))
    sha1: ((routing_sha1))

- type: replace
  path: /instance_groups/name=cassandra-brokers/jobs/name=route_registrar?
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: ((cf_deployment_name))
    properties:
      route_registrar:
        routes:
        - name: ((deployment_name))
          port: 8080
          registration_interval: 20s
          uris: [ ((cassandra_domain)) ]

# NOTE: Routing release v0.180.0 and above require BPM to be colocated with
# the 'route_registrar' job.
#
# See: https://github.com/cloudfoundry/routing-release/releases/tag/0.180.0
#
- path: /instance_groups/name=cassandra-brokers/jobs/name=bpm?
  type: replace
  value:
    name: bpm
    release: bpm


# Our Traefik reverse -proxy only accepts HTTPS requests.
# This enables the 'broker-registrar' errand to succeed

- path: /instance_groups/name=broker-registrar-vm/jobs/name=broker-registrar/consumes/servicebroker/properties/ssl_enabled
  type: replace
  value: true

- path: /instance_groups/name=broker-registrar-vm/jobs/name=broker-registrar/consumes/servicebroker/properties/skip_ssl_validation?
  type: replace
  value: true
