---


# Releases versions

- path: /releases/name=postgres
  type: replace
  value:
    name: postgres
    version: ((postgres_version))
    url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=((postgres_version))
    sha1: ((postgres_sha1))

- path: /releases/name=prometheus
  type: replace
  value:
    name: prometheus
    version: ((prometheus_version))
    url: https://bosh.io/d/github.com/cloudfoundry-community/prometheus-boshrelease?v=((prometheus_version))
    sha1: ((prometheus_sha1))
