---

# Customize URLs

- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/web?/external_url
  value: https://((alertmanager_hostname)).((cf_system_domain))

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/web?/external_url
  value: https://((prometheus_hostname)).((cf_system_domain))

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/server?/root_url
  value: https://((grafana_hostname)).((cf_system_domain))


# Customize routing setup

- type: replace
  path: /instance_groups/name=nginx/jobs/name=route_registrar/consumes/nats/deployment
  value: ((routing_deployment_name))

- type: replace
  path: /instance_groups/name=nginx/jobs/name=route_registrar/properties/route_registrar/routes/name=grafana/uris
  value: [ ((grafana_hostname)).((cf_system_domain)) ]

- type: replace
  path: /instance_groups/name=nginx/jobs/name=route_registrar/properties/route_registrar/routes/name=prometheus/uris
  value: [ ((prometheus_hostname)).((cf_system_domain)) ]

- type: replace
  path: /instance_groups/name=nginx/jobs/name=route_registrar/properties/route_registrar/routes/name=alertmanager/uris
  value: [ ((alertmanager_hostname)).((cf_system_domain)) ]


# Control release version

- path: /releases/name=routing?
  type: replace
  value:
    name: routing
    version: ((routing_version))
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=((routing_version))
    sha1: ((routing_sha1))

# NOTE: Routing release v0.180.0 and above require BPM to be colocated with
# the 'route_registrar' job.
#
# See: https://github.com/cloudfoundry/routing-release/releases/tag/0.180.0
#
- path: /instance_groups/name=nginx/jobs/name=bpm?
  type: replace
  value:
    name: bpm
    release: bpm

- path: /releases/name=bpm?
  type: replace
  value:
    name: bpm
    version: ((bpm_version))
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=((bpm_version))
    sha1: ((bpm_sha1))
