---
subsys:
  name: prometheus
  type: bosh-deployment
  deploy_after: cf

input_resources:
  - name: prometheus-boshrelease
    type: git
    uri: https://github.com/bosh-prometheus/prometheus-boshrelease.git
    version: v22.0.2


main_deployment_file: prometheus-boshrelease/manifests/prometheus.yml


operations_files:
  10.prometheus-boshrelease:
    # Bosh monitoring
    - manifests/operators/monitor-bosh
    - manifests/operators/enable-bosh-uaa

    # CF monitoring
    - manifests/operators/monitor-cf

    # CF integration
    - manifests/operators/enable-cf-route-registrar
    - manifests/operators/enable-grafana-uaa

    # If migration from Prometheus v1 is required
    # - manifests/operators/migrations/migrate_from_prometheus_1
  20.local:
    - set-versions
    # - expose-ports
    - customize-routing
    - scale-disks
    # - scale-disks-prometheus-v1 # only if 'migrate_from_prometheus_1' activated above


deployment_vars:
  deployment_name: easyfoundry-prometheus


  # User-facing settings

  grafana_domain: grafana.easyfoundry.prototyp.it
  prometheus_domain: prometheus.easyfoundry.prototyp.it
  alertmanager_domain: alertmanager.easyfoundry.prototyp.it

  metrics_environment: easyfoundry-demo


  # Versions

  prometheus_version: "22.0.2"
  prometheus_sha1: d813d755a1be7abbe2461ea9a7327235ed9a8996

  # postgres_version: "28"
  # postgres_sha1: c1fcec62cb9d2e95e3b191e3c91d238e2b9d23fa

  # routing_version: "0.175.0"
  # routing_sha1: 7314e7b070520561aef6fd4026501f3d23c5d67c

  # stemcell_name: bosh-warden-boshlite-ubuntu-trusty-go_agent
  # stemcell_version: "3541.12"
  # stemcell_sha1: 14bd6dd50d3caa913af97846eab39e5075b240d7


  # Reference declarations

  network_name: default
  prometheus_vm_extension: prometheus-loadbalancer


imported_vars:
  - subsys: concourse
    imports:

      # Versions

      - name: postgres_version
        from: depl-vars
        path: /postgres_version
      - name: postgres_sha1
        from: depl-vars
        path: /postgres_sha1


  - subsys: cf
    imports:

      # Versions

      - name: routing_version
        from: depl-vars
        path: /routing_version
      - name: routing_sha1
        from: depl-vars
        path: /routing_sha1

      - name: stemcell_name
        from: depl-vars
        path: /stemcell_name
      - name: stemcell_version
        from: depl-vars
        path: /stemcell_version
      - name: stemcell_sha1
        from: depl-vars
        path: /stemcell_sha1

      # CF routing plumbing

      - name: routing_deployment_name
        from: depl-vars
        path: /deployment_name


      # CF integration plumbing

      - name: uaa_clients_grafana_secret
        from: depl-creds
        path: /uaa_clients_grafana_secret

      - name: uaa_ssl
        from: depl-creds
        path: /uaa_ssl


      # CF Monitoring plumbing

      - name: metron_deployment_name
        from: depl-vars
        path: /deployment_name

      - name: system_domain
        from: depl-vars
        path: /system_domain


      - name: skip_ssl_verify
        from: depl-manifest
        path: /instance_groups/name=smoke-tests/jobs/name=smoke_tests/properties/smoke_tests/skip_ssl_validation

      - name: uaa_clients_cf_exporter_secret
        from: depl-creds
        path: /uaa_clients_cf_exporter_secret

      - name: uaa_clients_firehose_exporter_secret
        from: depl-creds
        path: /uaa_clients_firehose_exporter_secret

      - name: traffic_controller_external_port
        from: depl-manifest
        path: /instance_groups/name=log-api/jobs/name=route_registrar/properties/route_registrar/routes/name=doppler/port


  # Bosh monitoring plumbing

  - subsys: base-env
    imports:
      - name: bosh_url
        from: bbl-vars
        value: https://((internal_ip)):25555

      - name: bosh_ca_cert
        from: depl-creds
        path: /default_ca/certificate

      - name: uaa_bosh_exporter_client_secret
        from: depl-creds
        path: /uaa_bosh_exporter_client_secret
