---
subsys:
  name: prometheus
  type: bosh-deployment
  depends_on: [ cf ]

input_resources:
  - name: prometheus-boshrelease
    type: git
    uri: https://github.com/bosh-prometheus/prometheus-boshrelease.git
    version: v25.0.0


main_deployment_file: prometheus-boshrelease/manifests/prometheus.yml


operations_files:
  10_prometheus-boshrelease:
    # Bosh monitoring
    - manifests/operators/monitor-bosh
    - manifests/operators/enable-bosh-uaa
    - manifests/operators/monitor-node

    # CF monitoring
    - manifests/operators/monitor-cf
    # - manifests/operators/monitor-nats # TODO
    # - manifests/operators/monitor-mysql # TODO

    # CF Services monitoring
    # - manifests/operators/monitor-p-rabbitmq # TODO
    # - manifests/operators/monitor-p-redis # TODO
    # - manifests/operators/monitor-rabbitmq # TODO
    # - manifests/operators/monitor-redis # TODO
    # - manifests/operators/monitor-shield # TODO
    # - manifests/operators/monitor-mongodb # TODO
    # - manifests/operators/monitor-credhub # TODO
    # - manifests/operators/monitor-elasticsearch # TODO

    # - manifests/operators/monitor-concourse # TODO

    # CF integration
    - manifests/operators/enable-cf-route-registrar
    - manifests/operators/enable-grafana-uaa
  20_local:
    - rename-deployment-and-network
    - pin-stemcell
    - pin-versions
    - routing
    - scale-disks
    # - set-log-level


deployment_vars:
  deployment_name: easyfoundry-prometheus


  # User-facing settings

  grafana_hostname: monitoring        # under the CF system domain
  prometheus_hostname: prometheus     # under the CF system domain
  alertmanager_hostname: alertmanager # under the CF system domain

  metrics_environment: easyfoundry-demo


  # CF monitoring

  traffic_controller_external_port: 443


  # Versions

  prometheus_version: "25.0.0"
  prometheus_sha1: f2a1de6d1b00c856402964347685274877b33910


  # Reference declarations

  network_name: default
  prometheus_vm_extension: prometheus-loadbalancer


imported_vars:
  - subsys: concourse
    imports:

      # Versions

      - name: postgres_version
        from: depl-vars
        path: /postgres_version
      - name: postgres_sha1
        from: depl-vars
        path: /postgres_sha1


  - subsys: cf
    imports:

      # Versions

      - name: bpm_version
        from: depl-vars
        path: /bpm_version
      - name: bpm_sha1
        from: depl-vars
        path: /bpm_sha1

      - name: routing_version
        from: depl-vars
        path: /routing_version
      - name: routing_sha1
        from: depl-vars
        path: /routing_sha1

      - name: stemcell_os
        from: depl-vars
        path: /stemcell_os
      - name: stemcell_version
        from: depl-vars
        path: /stemcell_version
      - name: stemcell_sha1
        from: depl-vars
        path: /stemcell_sha1

      # CF routing plumbing

      - name: routing_deployment_name
        from: depl-vars
        path: /deployment_name

      - name: cf_system_domain
        from: vars-file
        file: private-config
        path: /system_domain


      # CF integration plumbing

      - name: uaa_clients_grafana_secret
        from: depl-creds
        path: /uaa_clients_grafana_secret

      - name: uaa_ssl
        from: depl-creds
        path: /uaa_ssl


      # CF Monitoring plumbing

      - name: metron_deployment_name
        from: depl-vars
        path: /deployment_name

      - name: system_domain
        from: vars-file
        file: private-config
        path: /system_domain


      - name: skip_ssl_verify
        from: depl-manifest
        path: /instance_groups/name=smoke-tests/jobs/name=smoke_tests/properties/smoke_tests/skip_ssl_validation

      - name: uaa_clients_cf_exporter_secret
        from: depl-creds
        path: /uaa_clients_cf_exporter_secret

      - name: uaa_clients_firehose_exporter_secret
        from: depl-creds
        path: /uaa_clients_firehose_exporter_secret


  # Bosh monitoring plumbing

  - subsys: base-env
    imports:
      - name: bosh_url
        from: bbl-vars
        value: https://((internal_ip)):25555

      - name: bosh_ca_cert
        from: depl-creds
        path: /default_ca/certificate

      - name: uaa_bosh_exporter_client_secret
        from: depl-creds
        path: /uaa_bosh_exporter_client_secret
