---

- name: Directories | main prefix dirs are created
  become: "{{ prefix_dir_must_become }}"
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ prefix_dir }}"
    - "{{ prefix_dir }}/bin"
  tags: [ directories ]

- name: Directories | resources dir is created
  become: "{{ resources_dir_must_become }}"
  file:
    dest: "{{ resources_dir }}"
    state: directory
  tags: [ directories ]

- name: Directories | local bin path is set up
  when: not prefix_dir_must_become
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    insertafter: EOF
    line: export PATH={{ prefix_dir }}/bin:$PATH
    state: present
  tags: [ directories ]
