azs:
- name: z1
- name: z2
- name: z3
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: minimal
  workers: 6
disk_types:
- disk_size: 1024
  name: 1GB
- disk_size: 5120
  name: 5GB
- disk_size: 10240
  name: 10GB
- disk_size: 100240
  name: 100GB
- disk_size: 2048
  name: shield
- disk_size: 2048
  name: 2GB
networks:
- name: default
  subnets:
  - azs:
    - z1
    - z2
    - z3
    cloud_properties:
      name: random
    gateway: 10.244.0.1
    range: 10.244.0.0/20
    reserved:
    - 10.244.0.1
    static:
    - 10.244.0.2 - 10.244.0.127
    - 10.244.1.0 - 10.244.1.127
    - 10.244.2.0 - 10.244.2.127
    - 10.244.3.0 - 10.244.3.127
- name: mysql-network
  subnets:
  - az: z1
    cloud_properties:
      name: random
    gateway: 10.244.17.1
    range: 10.244.17.0/24
  - az: z2
    cloud_properties:
      name: random
    gateway: 10.244.18.1
    range: 10.244.18.0/24
  - az: z3
    cloud_properties:
      name: random
    gateway: 10.244.19.1
    range: 10.244.19.0/24
- name: concourse-network
  subnets:
  - azs:
    - z1
    - z2
    - z3
    cloud_properties:
      name: random
    gateway: 10.244.16.1
    range: 10.244.16.0/24
    static:
    - 10.244.16.2 - 10.244.16.127
- name: shield-network
  subnets:
  - azs:
    - z1
    - z2
    - z3
    cloud_properties:
      name: random
    gateway: 10.244.204.1
    range: 10.244.204.0/24
    static:
    - 10.244.204.2 - 10.244.204.60
- name: cassandra-network
  subnets:
  - az: z1
    cloud_properties:
      name: random
    gateway: 10.244.67.1
    range: 10.244.67.0/24
    static:
    - 10.244.67.2 - 10.244.67.60
  - az: z2
    cloud_properties:
      name: random
    gateway: 10.244.68.1
    range: 10.244.68.0/24
    static:
    - 10.244.68.2 - 10.244.68.60
  - az: z3
    cloud_properties:
      name: random
    gateway: 10.244.69.1
    range: 10.244.69.0/24
    static:
    - 10.244.69.2 - 10.244.69.60
vm_extensions:
- name: 5GB_ephemeral_disk
- name: 10GB_ephemeral_disk
- name: 50GB_ephemeral_disk
- name: 100GB_ephemeral_disk
- name: 500GB_ephemeral_disk
- name: 1TB_ephemeral_disk
- cloud_properties:
    ports:
    - host: 80
    - host: 443
    - host: 2222
  name: ssh-proxy-and-router-lb
- cloud_properties:
    ports:
    - host: 1024-1123
  name: cf-tcp-router-network-properties
- cloud_properties:
    ports:
    - host: 8845
  name: credhub-lb
- cloud_properties:
    ports:
    - host: 3306
  name: mysql-proxy-lb
- cloud_properties:
    ports:
    - host: 8080
  name: concourse-atc-lb
- cloud_properties:
    ports:
    - host: 10443
  name: shield-core-lb
- cloud_properties:
    ports:
    - host: 3000
    - host: 9090
    - host: 9093
  name: prometheus-lb
vm_types:
- name: minimal
- name: small
- name: small-highmem
- name: default
- name: c3.large
- name: m3.large
- name: m3.medium
