---

- path: /name
  type: replace
  value: ((deployment_name))



- path: /instance_groups/name=minio/networks/name=default
  type: replace
  value:
    name: ((network_name))

- path: /instance_groups/name=tests/networks/name=default
  type: replace
  value:
    name: ((network_name))

- path: /instance_groups/name=bucket-seeding/networks/name=default
  type: replace
  value:
    name: ((network_name))
