---
name: scality

instance_groups:
  - name: s3server
    mograted_from: [ { name: scality } ]
    instances: 1
    azs: [ z1 ]
    jobs:
      - name: containers
        release: docker
        properties:
          containers:
            - name: s3server
              image: scality/s3server:6018536a # tagged 'RC7.2.0-rc4' 'BETA7.2.0'
              store_dir: /var/vcap/store/s3server
              volumes:
                - /var/vcap/store/s3server/data:/usr/src/app/localData
                - /var/vcap/store/s3server/metadata:/usr/src/app/localMetadata
              bind_ports:
                - ((s3server_tcp_port)):8000
              env_vars:
                # See config vars usage in:
                # <https://github.com/scality/cloudserver/blob/BETA7.2.0/docker-entrypoint.sh>
                - SCALITY_ACCESS_KEY_ID=((custom_account_access_key_id))
                - SCALITY_SECRET_ACCESS_KEY=((custom_account_secret_access_key))
                - LOG_LEVEL=debug # can be 'info', 'debug', or 'trace'
                - SSL=true
                - ENDPOINT=((s3server_endpoint_hostname))
                - LISTEN_ADDR=0.0.0.0

                # When only starting the stateless Zenko CloudServer, you can
                # configure the data and metadata servers to use.
                #
                # See: https://s3-server.readthedocs.io/en/latest/DOCKER.html#data-host-and-metadata-host
                #
                # - DATA_HOST=s3server-data
                # - METADATA_HOST=s3server-metadata

                # Use these variables to connect to the redis cache server on
                # another host:port than localhost:6379.
                #
                # See: https://s3-server.readthedocs.io/en/latest/DOCKER.html#redis-host
                #
                # - REDIS_HOST=redis-cache-server.example.com
                # - REDIS_PORT=6379
      - name: docker
        release: docker
        # properties:
        #   tcp_address: 0.0.0.0
        #   tls_cacert: "((docker-tls.ca))"
        #   tls_cert: "((docker-tls.certificate))"
        #   tls_key: "((docker-tls.private_key))"
    persistent_disk_type: 10GB
    vm_type: default
    stemcell: default
    networks:
      - name: default

variables:
  - name: custom_account_secret_access_key
    type: password

  - name: docker-ca
    type: certificate
    options:
      is_ca: true
      common_name: dockerCA
  - name: docker-tls
    type: certificate
    options:
      ca: docker-ca
      common_name: docker
      extended_key_usage:
        - client_auth

update:
  serial: true # instance groups to be deployed sequentially.

  canaries: 1
  canary_watch_time: 1000-60000

  max_in_flight: 1
  update_watch_time: 1000-60000

releases:
  - name: docker
    version: latest

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest
