---
name: cassandra

instance_groups:
  - name: cassandra-seeds
    instances: 3
    jobs:
      - name: cassandra
        release: *cassandra_release
        provides:
          seeds: { as: &cassandra_seeds_link cassandra_seeds_list }
        consumes:
          seeds: { from: *cassandra_seeds_link }
        properties: &cassandra_properties
          cluster_name: &cassandra_cluster_name bga_cluster
          num_tokens: 256
          internode_encryption_mode: none
          client_encryption_options:
            enabled: false
          max_heap_size: &cassandra_heap_size ((max_heap_size))
          heap_newsize: 800M
          cass_pwd: ((cassandra_admin_password))
          cassDbCertificate:
            ca: ((cassandra_certificate_seed.ca))
            private_key: ((cassandra_certificate_seed.private_key))
            certificate: ((cassandra_certificate_seed.certificate))
          cert:
            ca: ((cassandra_certificate_seed))
            private_key: ((cassandra_certificate_seed.private_key))
            certificate: ((cassandra_certificate_seed.certificate))
          cass_KSP: ((cassandra_key_store_pass))
          cass_version: 3.11.1
          topology:
            - 10.165.0.92=DC1:RAC1
            - 10.165.0.93=DC1:RAC1
            - 10.165.0.94=DC1:RAC1
            - 10.165.0.95=DC1:RAC1
    stemcell: *trusty_stemcell
    vm_type: &cassandra_vm_type default
    persistent_disk_type: &cassandra_disk_type 10GB
    env:
      persistent_disk_fs: xfs
      bosh: { swap_size: 0 }
    azs: [ z1 ]
    networks:
      - name: &cassandra_network ((network_name))

  # - name: cassandra-injectors
  #   instances: 0
  #   jobs:
  #     - name: cassandra_injector
  #       release: *cassandra_release
  #       properties: *cassandra_properties
  #   stemcell: *trusty_stemcell
  #   vm_type: *cassandra_vm_type
  #   persistent_disk_type: *cassandra_disk_type
  #   env:
  #     persistent_disk_fs: xfs
  #     bosh: { swap_size: 0 }
  #   azs: [ z1 ]
  #   networks:
  #     - name: *cassandra_network

  - name: cassandra-servers
    instances: 0
    jobs:
      - name: cassandra
        release: *cassandra_release
        consumes:
          seeds: { from: *cassandra_seeds_link }
        properties: # *cassandra_properties
          cluster_name: *cassandra_cluster_name
          num_tokens: 256
          internode_encryption_mode: none
          client_encryption_options:
            enabled: false
          max_heap_size: *cassandra_heap_size
          heap_newsize: 800M
          cass_pwd: ((cassandra_admin_password))
          cassDbCertificate:
            ca: ((cassandra_certificate_cluster.ca))
            private_key: ((cassandra_certificate_cluster.private_key))
            certificate: ((cassandra_certificate_cluster.certificate))
          cert:
            ca: ((cassandra_certificate_cluster))
            private_key: ((cassandra_certificate_cluster.private_key))
            certificate: ((cassandra_certificate_cluster.certificate))
          cass_KSP: ((cassandra_key_store_pass))
          cass_version: 3.11.1
          topology:
            - 10.165.0.92=DC1:RAC1
            - 10.165.0.93=DC1:RAC1
            - 10.165.0.94=DC1:RAC1
            - 10.165.0.95=DC1:RAC1
    stemcell: *trusty_stemcell
    vm_type: *cassandra_vm_type
    persistent_disk_type: *cassandra_disk_type
    env:
      persistent_disk_fs: xfs
      bosh: { swap_size: 0 }
    azs: [ z1 ]
    networks:
      - name: *cassandra_network

  - name: cassandra-brokers
    instances: 1
    jobs:
      - name: broker
        release: *cassandra_release
        consumes:
          seeds: { from: *cassandra_seeds_link }
        properties:
          broker:
            user: cassandra-broker
            password: ((cassandra_broker_password))
    stemcell: *trusty_stemcell
    vm_type: default
    # persistent_disk_type: *cassandra_disk_type # shouldn't be just 0 ? Come on, the broker is stateless!
    azs: [ z1 ]
    networks:
      - name: *cassandra_network

  - name: cassandra-smoke-tests
    instances: 1
    lifecycle: errand
    jobs:
      - name: broker-smoke-tests
        release: *cassandra_release
        properties:
          cf:
            api:
              url: ((cf_api_url))
            admin:
              username: ((cf_admin_username))
              password: ((cf_admin_password))
            skip:
              ssl:
                validation: ((cf_skip_ssl_validation))
            org: service-sandbox
            space: cassandra-smoke-tests
            cassandra:
              appdomain: ((cf_app_domain))
              servicename: cassandra
              serviceplan: default
              serviceinstancename: cassandra-instance
    stemcell: trusty
    vm_type: default
    # persistent_disk_type: default # shouldn't be just 0 ? Smoke tests should be stateless!
    azs: [ z1 ]
    networks:
      - name: *cassandra_network

variables:
  - name: cassandra_broker_password
    type: password
  - name: cassandra_admin_password
    type: password
  - name: cassandra_key_store_pass
    type: password

  - name: internalCA # /internalCA
    type: certificate
    options:
      is_ca: true
      common_name: internalCA

  - name: cassandra_certificate_seed
    type: certificate
    options:
      ca: internalCA # /internalCA
      common_name: <%= cassandra-seeds.instance.address %>
      alternative_names:
        - "*.cassandra-seeds.((network_name)).((deployment_name)).bosh"
      extended_key_usage: [ client_auth, server_auth ]

  # - name: cassandra_certificate_injector
  #   type: certificate
  #   options:
  #     ca: internalCA # /internalCA
  #     common_name: <%= cassandra-injectors.instance.address %>
  #     alternative_names:
  #       - "*.cassandra-injectors.((network_name)).((deployment_name)).bosh"
  #     extended_key_usage: [ client_auth, server_auth ]

  - name: cassandra_certificate_cluster
    type: certificate
    options:
      ca: internalCA # /internalCA
      common_name: <%= cassandra-servers.instance.address %>
      alternative_names:
        - "*.cassandra-servers.((network_name)).((deployment_name)).bosh"
      extended_key_usage: [ client_auth, server_auth ]


update:
  serial: true # instance groups to be deployed sequentially.

  canaries: 1
  canary_watch_time: 30000-240000

  max_in_flight: 1
  update_watch_time: 30000-240000


releases:
  - name: &cassandra_release cassandra39-services
    version: latest
  - name: broker-registrar
    version: latest
  - name: routing
    version: latest

stemcells:
  - alias: &trusty_stemcell trusty
    os: ubuntu-trusty
    version: latest
