---

- name: Virtualbox | bash-completion apt packages are installed
  become: yes
  apt:
    update_cache: yes
    package: [ bash-completion ]
    state: present

- name: Virtualbox | bash completion script is installed
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/bgandon/bash-completion-virtualbox/master/vboxmanage_completion.bash
    dest: /etc/bash_completion.d/vboxmanage_completion.bash
    mode: 0644
